# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_common', [dirname(__file__)])
        except ImportError:
            import _common
            return _common
        if fp is not None:
            try:
                _mod = imp.load_module('_common', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _common = swig_import_helper()
    del swig_import_helper
else:
    import _common
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def glErrorString(*args):
  return _common.glErrorString(*args)
glErrorString = _common.glErrorString

def glExtensionSupported(*args):
  return _common.glExtensionSupported(*args)
glExtensionSupported = _common.glExtensionSupported

def glGetInteger(*args):
  return _common.glGetInteger(*args)
glGetInteger = _common.glGetInteger

def checkGlError(*args):
  return _common.checkGlError(*args)
checkGlError = _common.checkGlError

def glSetMatrix(*args):
  return _common.glSetMatrix(*args)
glSetMatrix = _common.glSetMatrix

def glDrawQuad():
  return _common.glDrawQuad()
glDrawQuad = _common.glDrawQuad
class oglDisplayList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglDisplayList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oglDisplayList, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglDisplayList()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglDisplayList
    __del__ = lambda self : None;
    def isValid(self): return _common.oglDisplayList_isValid(self)
    def CompileBegin(self, *args): return _common.oglDisplayList_CompileBegin(self, *args)
    def CompileEnd(self): return _common.oglDisplayList_CompileEnd(self)
    def Execute(self): return _common.oglDisplayList_Execute(self)
oglDisplayList_swigregister = _common.oglDisplayList_swigregister
oglDisplayList_swigregister(oglDisplayList)

class oglDisplayListArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglDisplayListArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oglDisplayListArray, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglDisplayListArray()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglDisplayListArray
    __del__ = lambda self : None;
    def isValid(self): return _common.oglDisplayListArray_isValid(self)
    def Init(self, *args): return _common.oglDisplayListArray_Init(self, *args)
    def CompileBegin(self, *args): return _common.oglDisplayListArray_CompileBegin(self, *args)
    def CompileEnd(self): return _common.oglDisplayListArray_CompileEnd(self)
    def Execute(self, *args): return _common.oglDisplayListArray_Execute(self, *args)
    def ExecuteAll(self): return _common.oglDisplayListArray_ExecuteAll(self)
oglDisplayListArray_swigregister = _common.oglDisplayListArray_swigregister
oglDisplayListArray_swigregister(oglDisplayListArray)

class oglFont(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglFont, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oglFont, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglFont()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglFont
    __del__ = lambda self : None;
    def Load(self, *args): return _common.oglFont_Load(self, *args)
    def GetWidth(self, *args): return _common.oglFont_GetWidth(self, *args)
    def GetWidthf(self, *args): return _common.oglFont_GetWidthf(self, *args)
    def Print(self, *args): return _common.oglFont_Print(self, *args)
    def Printf(self, *args): return _common.oglFont_Printf(self, *args)
oglFont_swigregister = _common.oglFont_swigregister
oglFont_swigregister(oglFont)

class oglFrameBufferObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglFrameBufferObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oglFrameBufferObject, name)
    __repr__ = _swig_repr
    def CheckErrors(self): return _common.oglFrameBufferObject_CheckErrors(self)
    def __init__(self): 
        this = _common.new_oglFrameBufferObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglFrameBufferObject
    __del__ = lambda self : None;
    def Init(self, *args): return _common.oglFrameBufferObject_Init(self, *args)
    def InsertDepthAttachment(self, tex=None): return _common.oglFrameBufferObject_InsertDepthAttachment(self, tex)
    def InsertColorAttachment(self, *args): return _common.oglFrameBufferObject_InsertColorAttachment(self, *args)
    def Enable(self, set_viewport=False): return _common.oglFrameBufferObject_Enable(self, set_viewport)
    def Disable(self): return _common.oglFrameBufferObject_Disable(self)
    def Copy(self, *args): return _common.oglFrameBufferObject_Copy(self, *args)
    def CopyRegion(self, *args): return _common.oglFrameBufferObject_CopyRegion(self, *args)
    def GetWidth(self): return _common.oglFrameBufferObject_GetWidth(self)
    def GetHeight(self): return _common.oglFrameBufferObject_GetHeight(self)
    def GetColorTexture(self, *args): return _common.oglFrameBufferObject_GetColorTexture(self, *args)
    def GetColorTextureID(self, *args): return _common.oglFrameBufferObject_GetColorTextureID(self, *args)
    def GetColorAttachment(self, *args): return _common.oglFrameBufferObject_GetColorAttachment(self, *args)
    def GetColorCount(self): return _common.oglFrameBufferObject_GetColorCount(self)
    def GetDepthTextureID(self): return _common.oglFrameBufferObject_GetDepthTextureID(self)
    def GetDepthTexture(self, *args): return _common.oglFrameBufferObject_GetDepthTexture(self, *args)
    def GetFboId(self): return _common.oglFrameBufferObject_GetFboId(self)
oglFrameBufferObject_swigregister = _common.oglFrameBufferObject_swigregister
oglFrameBufferObject_swigregister(oglFrameBufferObject)

class oglShader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglShader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oglShader, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglShader()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglShader
    __del__ = lambda self : None;
    def Unload(self): return _common.oglShader_Unload(self)
    def Enable(self): return _common.oglShader_Enable(self)
    def Disable(self): return _common.oglShader_Disable(self)
    def GetAttribLocation(self, *args): return _common.oglShader_GetAttribLocation(self, *args)
    def GetUniformLocation(self, *args): return _common.oglShader_GetUniformLocation(self, *args)
    def isLoaded(self): return _common.oglShader_isLoaded(self)
oglShader_swigregister = _common.oglShader_swigregister
oglShader_swigregister(oglShader)

class oglTexture(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglTexture, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oglTexture, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _common.new_oglTexture(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglTexture
    __del__ = lambda self : None;
    def SetMinFilter(self, *args): return _common.oglTexture_SetMinFilter(self, *args)
    def SetMagFilter(self, *args): return _common.oglTexture_SetMagFilter(self, *args)
    def SetMinMagFilter(self, *args): return _common.oglTexture_SetMinMagFilter(self, *args)
    def isTextureValid(self): return _common.oglTexture_isTextureValid(self)
    def GetTexID(self): return _common.oglTexture_GetTexID(self)
    def Enable(self): return _common.oglTexture_Enable(self)
    def Bind(self, *args): return _common.oglTexture_Bind(self, *args)
    def Disable(self): return _common.oglTexture_Disable(self)
oglTexture_swigregister = _common.oglTexture_swigregister
oglTexture_swigregister(oglTexture)

class oglTexture1D(oglTexture):
    __swig_setmethods__ = {}
    for _s in [oglTexture]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglTexture1D, name, value)
    __swig_getmethods__ = {}
    for _s in [oglTexture]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, oglTexture1D, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglTexture1D()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglTexture1D
    __del__ = lambda self : None;
    def SetWrapS(self, *args): return _common.oglTexture1D_SetWrapS(self, *args)
    def TexImage1D(self, *args): return _common.oglTexture1D_TexImage1D(self, *args)
    def TexSubImage1D(self, *args): return _common.oglTexture1D_TexSubImage1D(self, *args)
    def CopyTexImage1D(self, *args): return _common.oglTexture1D_CopyTexImage1D(self, *args)
    def CopyTexSubImage1D(self, *args): return _common.oglTexture1D_CopyTexSubImage1D(self, *args)
oglTexture1D_swigregister = _common.oglTexture1D_swigregister
oglTexture1D_swigregister(oglTexture1D)

class oglTexture2D(oglTexture):
    __swig_setmethods__ = {}
    for _s in [oglTexture]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglTexture2D, name, value)
    __swig_getmethods__ = {}
    for _s in [oglTexture]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, oglTexture2D, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglTexture2D()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglTexture2D
    __del__ = lambda self : None;
    def SetWrapS(self, *args): return _common.oglTexture2D_SetWrapS(self, *args)
    def SetWrapT(self, *args): return _common.oglTexture2D_SetWrapT(self, *args)
    def SetWrapST(self, *args): return _common.oglTexture2D_SetWrapST(self, *args)
    def SetAutoMipmap(self, *args): return _common.oglTexture2D_SetAutoMipmap(self, *args)
    def SetBorderColor(self, *args): return _common.oglTexture2D_SetBorderColor(self, *args)
    def GetWrapS(self): return _common.oglTexture2D_GetWrapS(self)
    def GetWrapT(self): return _common.oglTexture2D_GetWrapT(self)
    def TexImage2DMipmap(self, *args): return _common.oglTexture2D_TexImage2DMipmap(self, *args)
    def TexImage2D(self, *args): return _common.oglTexture2D_TexImage2D(self, *args)
    def TexImage2DBorder(self, *args): return _common.oglTexture2D_TexImage2DBorder(self, *args)
    def TexSubImage2D(self, *args): return _common.oglTexture2D_TexSubImage2D(self, *args)
    def CopyTexImage2D(self, *args): return _common.oglTexture2D_CopyTexImage2D(self, *args)
    def CopyTexSubImage2D(self, *args): return _common.oglTexture2D_CopyTexSubImage2D(self, *args)
    def GetTexture(self, *args): return _common.oglTexture2D_GetTexture(self, *args)
    def DrawTexture(self): return _common.oglTexture2D_DrawTexture(self)
oglTexture2D_swigregister = _common.oglTexture2D_swigregister
oglTexture2D_swigregister(oglTexture2D)

class oglTexture3D(oglTexture):
    __swig_setmethods__ = {}
    for _s in [oglTexture]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglTexture3D, name, value)
    __swig_getmethods__ = {}
    for _s in [oglTexture]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, oglTexture3D, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglTexture3D()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglTexture3D
    __del__ = lambda self : None;
    def SetWrapR(self, *args): return _common.oglTexture3D_SetWrapR(self, *args)
    def SetWrapS(self, *args): return _common.oglTexture3D_SetWrapS(self, *args)
    def SetWrapT(self, *args): return _common.oglTexture3D_SetWrapT(self, *args)
    def TexImage3D(self, *args): return _common.oglTexture3D_TexImage3D(self, *args)
    def TexSubImage3D(self, *args): return _common.oglTexture3D_TexSubImage3D(self, *args)
    def CopyTexSubImage3D(self, *args): return _common.oglTexture3D_CopyTexSubImage3D(self, *args)
oglTexture3D_swigregister = _common.oglTexture3D_swigregister
oglTexture3D_swigregister(oglTexture3D)

class oglTextureRECT(oglTexture2D):
    __swig_setmethods__ = {}
    for _s in [oglTexture2D]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, oglTextureRECT, name, value)
    __swig_getmethods__ = {}
    for _s in [oglTexture2D]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, oglTextureRECT, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _common.new_oglTextureRECT()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _common.delete_oglTextureRECT
    __del__ = lambda self : None;
    def TexImage2D(self, *args): return _common.oglTextureRECT_TexImage2D(self, *args)
    def TexSubImage2D(self, *args): return _common.oglTextureRECT_TexSubImage2D(self, *args)
    def CopyTexImage2D(self, *args): return _common.oglTextureRECT_CopyTexImage2D(self, *args)
    def CopyTexSubImage2D(self, *args): return _common.oglTextureRECT_CopyTexSubImage2D(self, *args)
oglTextureRECT_swigregister = _common.oglTextureRECT_swigregister
oglTextureRECT_swigregister(oglTextureRECT)

# This file is compatible with both classic and new-style classes.


