#############################################################################
# Makefile for building: libcommon.so.1.0.0
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  common_lib.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile common_lib.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I./include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibin/build/common_lib/.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = common1.0.0
DISTDIR = /home/behollis/workspace/prosen-common/bin/build/common_lib/.obj/common1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -shared -Wl,-soname,libcommon.so.1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = bin/build/common_lib/.obj/

####### Files

SOURCES       = GL/oglTextureRECT.cpp \
		GL/oglTexture3D.cpp \
		GL/oglTexture2D.cpp \
		GL/oglTexture1D.cpp \
		GL/oglTexture.cpp \
		GL/oglFrameBufferObject.cpp \
		GL/oglCommon.cpp \
		GL/oglShader.cpp \
		SCI/Timer.cpp \
		SCI/Mat4.cpp \
		SCI/Subset.cpp \
		SCI/Graphics/MarchingCubes.cpp \
		SCI/Camera/ThirdPersonCameraControls.cpp \
		SCI/Camera/OrthoProjection.cpp \
		SCI/Camera/LookAt.cpp \
		SCI/Camera/FrustumProjection.cpp \
		SCI/Camera/FirstPersonCameraControls.cpp \
		SCI/Camera/CameraControls.cpp \
		SCI/Colormap.cpp \
		GL/oglFont.cpp \
		QT/QExtendedMainWindow.cpp \
		QT/QControlWidget.cpp \
		QT/QExtendedVerticalSlider.cpp \
		QT/QDoubleSlider.cpp \
		SCI/SimpleHistogram.cpp bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp \
		bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp \
		bin/build/common_lib/.moc/moc_Projection.cpp \
		bin/build/common_lib/.moc/moc_OrthoProjection.cpp \
		bin/build/common_lib/.moc/moc_FrustumProjection.cpp \
		bin/build/common_lib/.moc/moc_QControlWidget.cpp \
		bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp \
		bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp \
		bin/build/common_lib/.moc/moc_QDoubleSlider.cpp
OBJECTS       = bin/build/common_lib/.obj/oglTextureRECT.o \
		bin/build/common_lib/.obj/oglTexture3D.o \
		bin/build/common_lib/.obj/oglTexture2D.o \
		bin/build/common_lib/.obj/oglTexture1D.o \
		bin/build/common_lib/.obj/oglTexture.o \
		bin/build/common_lib/.obj/oglFrameBufferObject.o \
		bin/build/common_lib/.obj/oglCommon.o \
		bin/build/common_lib/.obj/oglShader.o \
		bin/build/common_lib/.obj/Timer.o \
		bin/build/common_lib/.obj/Mat4.o \
		bin/build/common_lib/.obj/Subset.o \
		bin/build/common_lib/.obj/MarchingCubes.o \
		bin/build/common_lib/.obj/ThirdPersonCameraControls.o \
		bin/build/common_lib/.obj/OrthoProjection.o \
		bin/build/common_lib/.obj/LookAt.o \
		bin/build/common_lib/.obj/FrustumProjection.o \
		bin/build/common_lib/.obj/FirstPersonCameraControls.o \
		bin/build/common_lib/.obj/CameraControls.o \
		bin/build/common_lib/.obj/Colormap.o \
		bin/build/common_lib/.obj/oglFont.o \
		bin/build/common_lib/.obj/QExtendedMainWindow.o \
		bin/build/common_lib/.obj/QControlWidget.o \
		bin/build/common_lib/.obj/QExtendedVerticalSlider.o \
		bin/build/common_lib/.obj/QDoubleSlider.o \
		bin/build/common_lib/.obj/SimpleHistogram.o \
		bin/build/common_lib/.obj/moc_QExtendedTcpSocket.o \
		bin/build/common_lib/.obj/moc_QExtendedTcpServer.o \
		bin/build/common_lib/.obj/moc_Projection.o \
		bin/build/common_lib/.obj/moc_OrthoProjection.o \
		bin/build/common_lib/.obj/moc_FrustumProjection.o \
		bin/build/common_lib/.obj/moc_QControlWidget.o \
		bin/build/common_lib/.obj/moc_QExtendedMainWindow.o \
		bin/build/common_lib/.obj/moc_QExtendedVerticalSlider.o \
		bin/build/common_lib/.obj/moc_QDoubleSlider.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		common_lib.pro SCI/Vex4.h \
		SCI/Vex3.h \
		SCI/Vex2.h \
		SCI/Mat4.h \
		SCI/Timer.h \
		SCI/Network/QExtendedTcpSocket.h \
		SCI/Subset.h \
		SCI/Network/QExtendedTcpServer.h \
		SCI/Utility.h \
		SCI/Graphics/MarchingCubes.h \
		SCI/BoundingBox.h \
		GL/oglTextureRECT.h \
		GL/oglTexture3D.h \
		GL/oglTexture2D.h \
		GL/oglTexture1D.h \
		GL/oglTexture.h \
		GL/oglFrameBufferObject.h \
		GL/oglCommon.h \
		GL/oglShader.h \
		SCI/Camera/ThirdPersonCameraControls.h \
		SCI/Camera/Projection.h \
		SCI/Camera/OrthoProjection.h \
		SCI/Camera/LookAt.h \
		SCI/Camera/FrustumProjection.h \
		SCI/Camera/FirstPersonCameraControls.h \
		SCI/Camera/CameraControls.h \
		SCI/Colormap.h \
		GL/oglFont.h \
		SCI/VexN.h \
		QT/QControlWidget.h \
		QT/QExtendedMainWindow.h \
		SCI/Geometry/CompGeom.h \
		GL/glext.h \
		QT/QExtendedVerticalSlider.h \
		QT/QDoubleSlider.h \
		SCI/SimpleHistogram.h GL/oglTextureRECT.cpp \
		GL/oglTexture3D.cpp \
		GL/oglTexture2D.cpp \
		GL/oglTexture1D.cpp \
		GL/oglTexture.cpp \
		GL/oglFrameBufferObject.cpp \
		GL/oglCommon.cpp \
		GL/oglShader.cpp \
		SCI/Timer.cpp \
		SCI/Mat4.cpp \
		SCI/Subset.cpp \
		SCI/Graphics/MarchingCubes.cpp \
		SCI/Camera/ThirdPersonCameraControls.cpp \
		SCI/Camera/OrthoProjection.cpp \
		SCI/Camera/LookAt.cpp \
		SCI/Camera/FrustumProjection.cpp \
		SCI/Camera/FirstPersonCameraControls.cpp \
		SCI/Camera/CameraControls.cpp \
		SCI/Colormap.cpp \
		GL/oglFont.cpp \
		QT/QExtendedMainWindow.cpp \
		QT/QControlWidget.cpp \
		QT/QExtendedVerticalSlider.cpp \
		QT/QDoubleSlider.cpp \
		SCI/SimpleHistogram.cpp
QMAKE_TARGET  = common
DESTDIR       = bin/libs/#avoid trailing-slash linebreak
TARGET        = libcommon.so.1.0.0
TARGETA       = bin/libs/libcommon.a
TARGET0       = libcommon.so
TARGETD       = libcommon.so.1.0.0
TARGET1       = libcommon.so.1
TARGET2       = libcommon.so.1.0


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

bin/libs/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d bin/libs/ || mkdir -p bin/libs/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) bin/libs/$(TARGET)
	-$(MOVE) $(TARGET)  bin/libs/ 
	-$(DEL_FILE) bin/libs/$(TARGET0)
	-$(DEL_FILE) bin/libs/$(TARGET1)
	-$(DEL_FILE) bin/libs/$(TARGET2)
	-$(MOVE) $(TARGET0) bin/libs/ 
	-$(MOVE) $(TARGET1) bin/libs/ 
	-$(MOVE) $(TARGET2) bin/libs/ 



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: common_lib.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		common_lib.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl
	$(QMAKE) -o Makefile common_lib.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
common_lib.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile common_lib.pro

qmake_all: FORCE


all: Makefile bin/libs/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents SCI/Vex4.h SCI/Vex3.h SCI/Vex2.h SCI/Mat4.h SCI/Timer.h SCI/Network/QExtendedTcpSocket.h SCI/Subset.h SCI/Network/QExtendedTcpServer.h SCI/Utility.h SCI/Graphics/MarchingCubes.h SCI/BoundingBox.h GL/oglTextureRECT.h GL/oglTexture3D.h GL/oglTexture2D.h GL/oglTexture1D.h GL/oglTexture.h GL/oglFrameBufferObject.h GL/oglCommon.h GL/oglShader.h SCI/Camera/ThirdPersonCameraControls.h SCI/Camera/Projection.h SCI/Camera/OrthoProjection.h SCI/Camera/LookAt.h SCI/Camera/FrustumProjection.h SCI/Camera/FirstPersonCameraControls.h SCI/Camera/CameraControls.h SCI/Colormap.h GL/oglFont.h SCI/VexN.h QT/QControlWidget.h QT/QExtendedMainWindow.h SCI/Geometry/CompGeom.h GL/glext.h QT/QExtendedVerticalSlider.h QT/QDoubleSlider.h SCI/SimpleHistogram.h $(DISTDIR)/
	$(COPY_FILE) --parents GL/oglTextureRECT.cpp GL/oglTexture3D.cpp GL/oglTexture2D.cpp GL/oglTexture1D.cpp GL/oglTexture.cpp GL/oglFrameBufferObject.cpp GL/oglCommon.cpp GL/oglShader.cpp SCI/Timer.cpp SCI/Mat4.cpp SCI/Subset.cpp SCI/Graphics/MarchingCubes.cpp SCI/Camera/ThirdPersonCameraControls.cpp SCI/Camera/OrthoProjection.cpp SCI/Camera/LookAt.cpp SCI/Camera/FrustumProjection.cpp SCI/Camera/FirstPersonCameraControls.cpp SCI/Camera/CameraControls.cpp SCI/Colormap.cpp GL/oglFont.cpp QT/QExtendedMainWindow.cpp QT/QControlWidget.cpp QT/QExtendedVerticalSlider.cpp QT/QDoubleSlider.cpp SCI/SimpleHistogram.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) bin/libs/$(TARGET) 
	-$(DEL_FILE) bin/libs/$(TARGET0) bin/libs/$(TARGET1) bin/libs/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp bin/build/common_lib/.moc/moc_Projection.cpp bin/build/common_lib/.moc/moc_OrthoProjection.cpp bin/build/common_lib/.moc/moc_FrustumProjection.cpp bin/build/common_lib/.moc/moc_QControlWidget.cpp bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp bin/build/common_lib/.moc/moc_QDoubleSlider.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp bin/build/common_lib/.moc/moc_Projection.cpp bin/build/common_lib/.moc/moc_OrthoProjection.cpp bin/build/common_lib/.moc/moc_FrustumProjection.cpp bin/build/common_lib/.moc/moc_QControlWidget.cpp bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp bin/build/common_lib/.moc/moc_QDoubleSlider.cpp
bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp: SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		SCI/Network/QExtendedTcpSocket.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SCI/Network/QExtendedTcpSocket.h -o bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp

bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp: SCI/Network/QExtendedTcpServer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SCI/Network/QExtendedTcpServer.h -o bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp

bin/build/common_lib/.moc/moc_Projection.cpp: SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		SCI/Camera/Projection.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SCI/Camera/Projection.h -o bin/build/common_lib/.moc/moc_Projection.cpp

bin/build/common_lib/.moc/moc_OrthoProjection.cpp: SCI/Camera/Projection.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		SCI/Camera/OrthoProjection.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SCI/Camera/OrthoProjection.h -o bin/build/common_lib/.moc/moc_OrthoProjection.cpp

bin/build/common_lib/.moc/moc_FrustumProjection.cpp: SCI/Camera/Projection.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		SCI/Camera/FrustumProjection.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SCI/Camera/FrustumProjection.h -o bin/build/common_lib/.moc/moc_FrustumProjection.cpp

bin/build/common_lib/.moc/moc_QControlWidget.cpp: QT/QDoubleSlider.h \
		QT/QExtendedVerticalSlider.h \
		QT/QControlWidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include QT/QControlWidget.h -o bin/build/common_lib/.moc/moc_QControlWidget.cpp

bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp: QT/QExtendedMainWindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include QT/QExtendedMainWindow.h -o bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp

bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp: QT/QExtendedVerticalSlider.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include QT/QExtendedVerticalSlider.h -o bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp

bin/build/common_lib/.moc/moc_QDoubleSlider.cpp: QT/QDoubleSlider.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/behollis/workspace/prosen-common -I/home/behollis/workspace/prosen-common/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include QT/QDoubleSlider.h -o bin/build/common_lib/.moc/moc_QDoubleSlider.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bin/build/common_lib/.obj/oglTextureRECT.o: GL/oglTextureRECT.cpp GL/oglTextureRECT.h \
		GL/oglCommon.h \
		GL/oglTexture2D.h \
		GL/oglTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglTextureRECT.o GL/oglTextureRECT.cpp

bin/build/common_lib/.obj/oglTexture3D.o: GL/oglTexture3D.cpp GL/glew.h \
		GL/oglTexture3D.h \
		GL/oglCommon.h \
		GL/oglTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglTexture3D.o GL/oglTexture3D.cpp

bin/build/common_lib/.obj/oglTexture2D.o: GL/oglTexture2D.cpp GL/oglTexture2D.h \
		GL/oglCommon.h \
		GL/oglTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglTexture2D.o GL/oglTexture2D.cpp

bin/build/common_lib/.obj/oglTexture1D.o: GL/oglTexture1D.cpp GL/oglTexture1D.h \
		GL/oglCommon.h \
		GL/oglTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglTexture1D.o GL/oglTexture1D.cpp

bin/build/common_lib/.obj/oglTexture.o: GL/oglTexture.cpp GL/oglTexture.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglTexture.o GL/oglTexture.cpp

bin/build/common_lib/.obj/oglFrameBufferObject.o: GL/oglFrameBufferObject.cpp GL/glew.h \
		GL/oglFrameBufferObject.h \
		GL/oglCommon.h \
		GL/oglTexture2D.h \
		GL/oglTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglFrameBufferObject.o GL/oglFrameBufferObject.cpp

bin/build/common_lib/.obj/oglCommon.o: GL/oglCommon.cpp GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglCommon.o GL/oglCommon.cpp

bin/build/common_lib/.obj/oglShader.o: GL/oglShader.cpp GL/glew.h \
		GL/oglShader.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglShader.o GL/oglShader.cpp

bin/build/common_lib/.obj/Timer.o: SCI/Timer.cpp SCI/Timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/Timer.o SCI/Timer.cpp

bin/build/common_lib/.obj/Mat4.o: SCI/Mat4.cpp SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/Mat4.o SCI/Mat4.cpp

bin/build/common_lib/.obj/Subset.o: SCI/Subset.cpp SCI/Subset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/Subset.o SCI/Subset.cpp

bin/build/common_lib/.obj/MarchingCubes.o: SCI/Graphics/MarchingCubes.cpp SCI/Graphics/MarchingCubes.h \
		SCI/Vex3.h \
		SCI/Vex2.h \
		SCI/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/MarchingCubes.o SCI/Graphics/MarchingCubes.cpp

bin/build/common_lib/.obj/ThirdPersonCameraControls.o: SCI/Camera/ThirdPersonCameraControls.cpp SCI/Camera/ThirdPersonCameraControls.h \
		SCI/Camera/CameraControls.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		SCI/Camera/LookAt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/ThirdPersonCameraControls.o SCI/Camera/ThirdPersonCameraControls.cpp

bin/build/common_lib/.obj/OrthoProjection.o: SCI/Camera/OrthoProjection.cpp SCI/Camera/OrthoProjection.h \
		SCI/Camera/Projection.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/OrthoProjection.o SCI/Camera/OrthoProjection.cpp

bin/build/common_lib/.obj/LookAt.o: SCI/Camera/LookAt.cpp SCI/Camera/LookAt.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/LookAt.o SCI/Camera/LookAt.cpp

bin/build/common_lib/.obj/FrustumProjection.o: SCI/Camera/FrustumProjection.cpp SCI/Camera/FrustumProjection.h \
		SCI/Camera/Projection.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/FrustumProjection.o SCI/Camera/FrustumProjection.cpp

bin/build/common_lib/.obj/FirstPersonCameraControls.o: SCI/Camera/FirstPersonCameraControls.cpp SCI/Camera/FirstPersonCameraControls.h \
		SCI/Camera/CameraControls.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h \
		SCI/Camera/LookAt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/FirstPersonCameraControls.o SCI/Camera/FirstPersonCameraControls.cpp

bin/build/common_lib/.obj/CameraControls.o: SCI/Camera/CameraControls.cpp SCI/Camera/CameraControls.h \
		SCI/Mat4.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		SCI/Vex3.h \
		SCI/Vex4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/CameraControls.o SCI/Camera/CameraControls.cpp

bin/build/common_lib/.obj/Colormap.o: SCI/Colormap.cpp SCI/Colormap.h \
		SCI/Vex4.h \
		SCI/Vex3.h \
		SCI/Vex2.h \
		SCI/Utility.h \
		GL/oglFont.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/Colormap.o SCI/Colormap.cpp

bin/build/common_lib/.obj/oglFont.o: GL/oglFont.cpp GL/oglFont.h \
		GL/oglCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/oglFont.o GL/oglFont.cpp

bin/build/common_lib/.obj/QExtendedMainWindow.o: QT/QExtendedMainWindow.cpp QT/QExtendedMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/QExtendedMainWindow.o QT/QExtendedMainWindow.cpp

bin/build/common_lib/.obj/QControlWidget.o: QT/QControlWidget.cpp QT/QControlWidget.h \
		QT/QDoubleSlider.h \
		QT/QExtendedVerticalSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/QControlWidget.o QT/QControlWidget.cpp

bin/build/common_lib/.obj/QExtendedVerticalSlider.o: QT/QExtendedVerticalSlider.cpp QT/QExtendedVerticalSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/QExtendedVerticalSlider.o QT/QExtendedVerticalSlider.cpp

bin/build/common_lib/.obj/QDoubleSlider.o: QT/QDoubleSlider.cpp QT/QDoubleSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/QDoubleSlider.o QT/QDoubleSlider.cpp

bin/build/common_lib/.obj/SimpleHistogram.o: SCI/SimpleHistogram.cpp SCI/SimpleHistogram.h \
		SCI/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/SimpleHistogram.o SCI/SimpleHistogram.cpp

bin/build/common_lib/.obj/moc_QExtendedTcpSocket.o: bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_QExtendedTcpSocket.o bin/build/common_lib/.moc/moc_QExtendedTcpSocket.cpp

bin/build/common_lib/.obj/moc_QExtendedTcpServer.o: bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_QExtendedTcpServer.o bin/build/common_lib/.moc/moc_QExtendedTcpServer.cpp

bin/build/common_lib/.obj/moc_Projection.o: bin/build/common_lib/.moc/moc_Projection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_Projection.o bin/build/common_lib/.moc/moc_Projection.cpp

bin/build/common_lib/.obj/moc_OrthoProjection.o: bin/build/common_lib/.moc/moc_OrthoProjection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_OrthoProjection.o bin/build/common_lib/.moc/moc_OrthoProjection.cpp

bin/build/common_lib/.obj/moc_FrustumProjection.o: bin/build/common_lib/.moc/moc_FrustumProjection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_FrustumProjection.o bin/build/common_lib/.moc/moc_FrustumProjection.cpp

bin/build/common_lib/.obj/moc_QControlWidget.o: bin/build/common_lib/.moc/moc_QControlWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_QControlWidget.o bin/build/common_lib/.moc/moc_QControlWidget.cpp

bin/build/common_lib/.obj/moc_QExtendedMainWindow.o: bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_QExtendedMainWindow.o bin/build/common_lib/.moc/moc_QExtendedMainWindow.cpp

bin/build/common_lib/.obj/moc_QExtendedVerticalSlider.o: bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_QExtendedVerticalSlider.o bin/build/common_lib/.moc/moc_QExtendedVerticalSlider.cpp

bin/build/common_lib/.obj/moc_QDoubleSlider.o: bin/build/common_lib/.moc/moc_QDoubleSlider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/build/common_lib/.obj/moc_QDoubleSlider.o bin/build/common_lib/.moc/moc_QDoubleSlider.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

